### ISSUE TITLE
Кр 1 (midterm осень 2017г)

### ISSUE THREAD

**Issue by Demushkina** [bdemeshev/pr201#3]
Буду техать решения кр-1 по теории вероятности, осень 2017г

**Comment by Demushkina** [comment]
By Аня Демушкина БЭК162

**Comment by bdemeshev** [comment]
Аня, спасибо большое!!

в этом репозитории только какие-то внезапные мелочи для семинаров :)
Три разумных вещи в создании которых можно поучаствовать:
- [подборка экзаменов](https://github.com/bdemeshev/probability_hse_exams)
- [сборник красивых задач](https://github.com/bdemeshev/probability_dna)
- [материалы семинаров](https://github.com/bdemeshev/probability_pro)

Тебе скорее всего первая :)

И можешь либо по всем правилам делать pull-request, либо просто сбросить тех в комментах к [issue 19](https://github.com/bdemeshev/probability_hse_exams/issues/19).
